{% set name = "django-prose-editor" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django_prose_editor-{{ version }}.tar.gz
  sha256: 5e5cad50699ffde0f04b5c6e17b64d52b9deeef84282fa988ab742d3025bb699

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - hatchling
    - pip
  run:
    - python >=3.11
    - django >=4.2

test:
  imports:
    - django_prose_editor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/matthiask/django-prose-editor/
  summary: Prose editor for the Django admin based on ProseMirror
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
