{% set python_min = "3.10" %}
{% set name = "django-prose-editor" %}
{% set version = "0.10.4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_prose_editor-{{ version }}.tar.gz
  sha256: 53a3a1e6b43562018c916ff4a63ed517b6fe7b42ff0e861a06ee6100216ec0e3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - django >=4.2
    - django-js-asset >=3.0.1

test:
  imports:
    - django_prose_editor
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/matthiask/django-prose-editor/
  summary: Prose editor for the Django admin based on ProseMirror
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
