{% set name = "django-prose-editor" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django_prose_editor-{{ version }}.tar.gz
  sha256: 6a21752f3dc6a1c796a352aef5d9398433cba722209633089e6d10f767a16013

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - hatchling
    - pip
  run:
    - python >=3.11
    - django >=4.2
    - django-js-asset

test:
  imports:
    - django_prose_editor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/matthiask/django-prose-editor/
  summary: Prose editor for the Django admin based on ProseMirror
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
