schema_version: 1

context:
  name: django-prose-editor
  version: "0.27.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_prose_editor-${{ version }}.tar.gz
  sha256: 8cf8ccb48cf1422373cc924ae08e987d2ed11f6c0256c556323d6d4d49eebdc8

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - django >=4.2
    - django-js-asset >=4

tests:
  - python:
      imports:
        - django_prose_editor
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Prose editor for the Django admin based on ProseMirror
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/matthiask/django-prose-editor/

extra:
  recipe-maintainers:
    - thewchan
